workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: "17"
      android:
        build_dir: "app"
    scripts:
      - name: Set Java version
        script: |
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac

      - name: Clean project
        script: ./gradlew clean

      - name: Build APK debug
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - "YOUR_EMAIL@example.com"
