workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
    scripts:
      - name: Set Java 17
        script: |
          export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
          export PATH="$JAVA_HOME/bin:$PATH"
          java -version

      - name: Make gradlew executable
        script: chmod +x ./gradlew

      - name: Clean project
        script: ./gradlew clean

      - name: Build APK (Debug)
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
